devices:
  samplerate: 44100
  buffersize: 2048
  silence_threshold: -60
  silence_timeout: 3.0

  capture:
    type: Alsa
    channels: 2
    device: hw:Loopback,0
    format: S32LE

  playback:
    type: Alsa
    channels: 2
    device: hw:0,0
    format: S16LE

filters:
  volume:
    parameters:
      ramp_time: 200
    type: Volume
mixers:
  2x2:
    channels:
      in: 2
      out: 2
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
pipeline:
- name: 2x2
  type: Mixer
- channel: 0
  names:
  - volume
  type: Filter
- channel: 1
  names:
  - volume
  type: Filter
